audio:
  sample_rate: 16000
  n_fft: 1024
  hop_length: 256
  win_length: 1024
  n_mels: 80
  f_min: 0
  f_max: 8000
  max_wave_length: 48000  # 3 seconds at 16kHz

model:
  embedding_dim: 256
  encoder_channels: [64, 128, 256, 256]
  encoder_kernel_sizes: [5, 5, 5, 5]
  encoder_strides: [2, 2, 2, 2]
  transformer_heads: 8
  transformer_layers: 6
  transformer_ff_dim: 1024
  decoder_channels: [256, 128, 64, 1]
  decoder_kernel_sizes: [5, 5, 5, 5]
  decoder_strides: [2, 2, 2, 2]

training:
  batch_size: 16
  learning_rate: 0.0001
  epochs: 50
  save_every: 5
  num_workers: 4
  device: "cuda"  # Will be handled in Python code

data:
  path: "./data"
